openapi: 3.0.0
info:
  version: "1.0"
  title: Desafio Full Stack Coodesh
  description: "REST API do desafio full stack"
servers:
  - url: "http://localhost:3000"
components:
  securitySchemes:
    JWT:
      description: ""
      type: "apiKey"
      name: "Authorization"
      in: "header"
tags:
  - name: User
    description: Dados de todos usuário cadastrados na base de dados
paths:
  /users:
    get:
      summary: Endpoint que retorna todos os usuários cadastrados na base de dados
      parameters:
        - in: query
          name: offset
          schema:
            type: integer
          description: "Pagina que você quer acessar"
        - in: query
          name: limit
          schema:
            type: integer
          description: O número de itens a serem retornados
      responses:
        200:
          description: Retorna todos os dados usuários
          content:
            application/json:
              schema:
                allOf:
                  - $ref: "./schemas/users.yaml"
        401:
          $ref: "./responses/not_found_credentials.yaml"
  /users/{id}:
    get:
      summary: Endpoint que retorna um usuário baseado no seu id
      parameters:
        - in: path
          name: id
          required: true
          description: "id do usuário que vai ser pesquisado"
      responses:
        200:
          description: Retorna todos os dados usuários
          content:
            application/json:
              schema:
                allOf:
                  - $ref: "./schemas/user.yaml"
        404:
         $ref: "./responses/user_not_found.yaml"

  /users/{id }:
    delete:
      parameters:
        - in: path
          name: id
          required: true
          description: "id do usuário que vai ser deletado"
        - in: header
          name: Authorization
          schema:
            type: string
          required: true
          description: Autorização por meio do token de acesso
          example: "e07fbaae3b8242d8986c486d01018ca47b83"
      responses:
        202:
          $ref: "./responses/user_deleted.yaml"
        404:
          $ref: "./responses/user_not_found.yaml"